"""Tabulate the scaled sweep: for each audit, the median metric per
ensemble at T/n = 1, 2 and 8, side by side for every n that has results,
plus the verdict flips between the smallest and largest n and the
provenance block (exclusions, PSD floors, numerical ranks, timings).

Writes SCALE.md beside the results. Run scale_sweep.py first.

Run: python papers/measure_audit/scale_summary.py
"""
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
NS = [30, 100, 300, 1000, 3000]
# kept as curiosities: generators native to this package rather than to a
# published method. Tabulated and plotted, but out of the headline counts.
PACKAGE_NATIVE = {"residuals", "walk", "animals"}
RATIOS = [1, 2, 8]
AUDITS = [
    ("lw", "Ledoit-Wolf shrinkage intensity", None),
    ("clip", "MP clipping vs raw correlation (Frobenius ratio)", 1.0),
    ("hrp", "HRP vs long-only min-var (true variance ratio)", 1.0),
    ("load", "loaded vs unloaded MVDR (true output power ratio)", 1.0),
    ("gl", "cross-validated graphical lasso vs Ledoit-Wolf "
           "(precision loss ratio)", 1.0),
    ("glf", "fixed-penalty graphical lasso vs Ledoit-Wolf "
            "(precision loss ratio)", 1.0),
    ("taper", "Gaspari-Cohn taper vs raw (Frobenius ratio)", 1.0),
]

results, metas = {}, {}
for n in NS:
    p = os.path.join(HERE, f"regime_results_n{n}.json")
    if os.path.exists(p):
        results[n] = json.load(open(p))
        raw = os.path.join(HERE, f"regime_raw_n{n}.json")
        if os.path.exists(raw):
            metas[n] = json.load(open(raw))["meta"]
present = [n for n in NS if n in results]
ens_order = metas[present[0]]["ensembles"] if present else []


def cell(n, audit, e, ratio):
    s = results[n].get(audit, {}).get(e, {})
    return s.get(str(int(round(ratio * n))))


def fmt(v):
    if v is None:
        return "  --  "
    if abs(v) >= 1e4:
        return f"{v:.1e}"
    return f"{v:.3f}" if abs(v) < 100 else f"{v:.1f}"


lines = ["# The scaled regime sweep", "",
         "Six audits over the dimension x regime grid: n in "
         + ", ".join(str(n) for n in present)
         + " crossed with T/n in 0.5, 1, 2, 4, 8, medians over "
         + f"{metas[present[0]]['reps']} seeded draws per cell. Generated by "
           "`scale_summary.py` from `scale_sweep.py` output; figure via "
           "`scale_matrix.py`.", ""]

for key, title, ref in AUDITS:
    lines += [f"## {key} — {title}", ""]
    if ref is not None:
        lines += [f"Values above {ref:.0f} mean the recommended treatment "
                  "loses to the untreated baseline.", ""]
    head = "| ensemble | " + " | ".join(
        f"n={n}, T/n={r}" for n in present for r in RATIOS) + " |"
    lines += [head, "|" + "---|" * (1 + len(present) * len(RATIOS))]
    for e in ens_order:
        row = [fmt(cell(n, key, e, r)) for n in present for r in RATIOS]
        tag = " †" if e in PACKAGE_NATIVE else ""
        lines.append(f"| `{e}`{tag} | " + " | ".join(row) + " |")
    lines += ["", "† package-native curiosity: kept for interest, excluded "
                  "from the verdict counts.", ""]

    if ref is not None and len(present) > 1:
        lo, hi = present[0], present[-1]
        flips = []
        for e in ens_order:
            if e in PACKAGE_NATIVE:
                continue
            a, b = cell(lo, key, e, 2), cell(hi, key, e, 2)
            if a is not None and b is not None and (a > ref) != (b > ref):
                flips.append(f"`{e}` ({fmt(a)} -> {fmt(b)})")
        lines += [f"Verdict flips at T/n = 2 between n = {lo} and n = {hi}, "
                  "literature ensembles: "
                  + (", ".join(flips) if flips else "none") + ".", ""]

lines += ["## Provenance", ""]
for n in present:
    m = metas.get(n, {})
    rk = m.get("median_numerical_rank", {})
    degenerate = sorted(f"`{e}` {int(v)}/{n}" for e, v in rk.items()
                        if v < 0.9 * n)
    reps_seen = list((m.get("reps_by_ensemble") or {}).values()) or [
        m.get("reps", 0)]

    def has(audit):
        return any(results[n].get(audit, {}).values())
    lines += [
        f"### n = {n}", "",
        f"- reps {min(reps_seen)}-{max(reps_seen)} per ensemble, T grid "
        f"{m.get('TS')}; last pass {m.get('wall_seconds', 0)/60:.0f} min on "
        f"{m.get('workers')} workers",
        f"- ensembles run: {len(m.get('ensembles', []))}"
        + (f"; excluded {', '.join('`'+x+'`' for x in m['excluded_generators'])}"
           f" ({m.get('excluded_reason')})" if m.get("excluded_generators")
           else ""),
        # read presence off the data, not off the last pass's flags: these
        # files are built up by merging several passes
        f"- cross-validated glasso: {'present' if has('gl') else 'not run'}"
        + ("" if has("gl") else
           " (a single fit runs into the hour at this n)"),
        f"- fixed-penalty glasso: "
        f"{'present' if has('glf') else 'not run'}",
        "- truths needing a PSD floor: "
        + (", ".join("`" + e + "`" for e in m.get("psd_floored_ensembles", []))
           or "none"),
        "- numerically rank-deficient truths: "
        + (", ".join(degenerate) or "none"),
        f"- failed cells: {len(m.get('failed_cells', []))}",
    ]
    gaps = m.get("incomplete_coverage", {})
    lines.append("- incomplete audit coverage: "
                 + (", ".join(f"`{k}` {v}" for k, v in sorted(gaps.items()))
                    or "none"))
    # the fixed-penalty glasso cannot always be solved at its theory alpha;
    # where it was rescued, say so and by what
    resc = {}
    for k, c in (m.get("solver_notes") or {}).items():
        parts = k.split()
        if len(parts) >= 2 and parts[1].startswith("glf_"):
            kind = "ridge" if parts[1] == "glf_ridge" else "higher alpha"
            resc.setdefault(parts[0], {})
            resc[parts[0]][kind] = resc[parts[0]].get(kind, 0) + c
    if resc:
        lines.append("- fixed-penalty glasso rescued off its theory alpha: "
                     + ", ".join(
                         f"`{e}` (" + ", ".join(f"{v} by {kind}"
                                                for kind, v in sorted(d.items()))
                         + ")" for e, d in sorted(resc.items())))
    lines.append("")

out = os.path.join(HERE, "SCALE.md")
with open(out, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {out}")

# a compact console view of how often each claim loses, by n
print("\nfraction of (ensemble, T) cells where the treatment loses, over the "
      "literature ensembles [all ensembles incl. curiosities]:")
print("audit  " + "".join(f"        n={n}" for n in present))
for key, _, ref in AUDITS:
    if ref is None:
        continue
    row = []
    for n in present:
        lit = [v for e, s in results[n].get(key, {}).items()
               if e not in PACKAGE_NATIVE for v in s.values()]
        allv = [v for e, s in results[n].get(key, {}).items()
                for v in s.values()]
        row.append(f" {np.mean(np.array(lit) > ref):6.2f} "
                   f"[{np.mean(np.array(allv) > ref):5.2f}]" if lit
                   else "      --      ")
    print(f"{key:6s}" + "".join(row))
